language: node_js
sudo: required
services:
  - docker
before_install:
  - docker build -t mameazad/docker-react -f Dockerfile.dev .

script:
  - docker run mameazad/docker-react npm run test -- --coverage