language: node_js
sudo: required
services:
  - docker
before_install:
  - docker build -t mameazad/docker-react -f Dockerfile.dev .

script:
  - docker run mameazad/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-708543611800"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
  secure: "$AWS_SECRET_KEY"
