name: Deploy Frontend
on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main" ]
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secret.DOCKERHUB_USERNAME }}
          password: ${{ secret.DOCKERHUB_TOKEN}}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image for Development env
      run: docker build .  --tag mameazad/docker-react --file Dockerfile.dev
